#
# File: Common_Costmap.yaml
# Author: @AlessioBorgi
# Date: 20-02-2024

# Description: This is a file containing the parameters common to both the Global and Local Costmap.
#

obstacle_range: 2.5
raytrace_range: 3.0

footprint: [[0.1,0.1], [0.1,-0.2],[-0.1,-0.2],[-0.1,0.1]]
inflation_radius: 0.1
