#
# File: TrajectoryPlanner_Local.yaml
# Author: @AlessioBorgi
# Date: 20-02-2024

# Description: This is a file containing the parameters of the Local Planner. In this case, we are implementing the Base Planner
#              "TrajectoryPlannerROS".
#


base_local_planner: base_local_planner/TrajectoryPlannerROS

TrajectoryPlannerROS:
    max_vel_x: 0.45
    min_vel_x: 0.1
    max_vel_theta: 1.0
    min_in_place_vel_theta: 0.4
  
    acc_lim_theta: 3.2
    acc_lim_x: 2.5
    acc_lim_y: 2.5
  
    holonomic_robot: true